#!/usr/bin/env node
// `migrate` v2 -> v3 (plan SS18; PAR-MIGRATE-CLASSIFY, PAR-BROWNFIELD-SAFETY, PAR-MIGRATION-REVERT).
//   plan    read-only. Classifies every file with the Hash DB (parity/migrate-inventory.mjs) and says what would happen.
//   apply   writes the migration into the working tree for ONE reviewable PR: retires platform-owned files that are
//           byte-identical to a TEMPLATE tag, adds ai-native.lock.json + the v3 adapter files + the L3 caller workflow.
//           It never deletes a MODIFIED or LOCAL file, never touches runs/, .audit/, ROADMAP.md, STATUS.md or product-owned
//           files, never runs `git clean` and never rewrites history. A v3 file that would overwrite a user's file is a
//           collision that BLOCKS unless the user decided `keep` for it.
//   revert  restores exactly what apply removed (from the base commit recorded in the journal) and removes exactly what
//           apply created, if the user has not edited it since; a missing journal is an error.
//   node runtime/migrate/migrate.mjs plan|apply|revert --target <dir> [--repo github:o/r --version vX --commit <sha> --digest sha256:.. --profile <id>]
//        [--tool claude|codex|opencode]... [--base-branch main] [--keep <path>]... [--json]
import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { constants, copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { consumerFiles } from "../adapters/consumer.mjs";
import { canonical, readLock, LOCK_FILE } from "../bootstrap/install.mjs";
import { globToRegExp } from "../gates/control-plane.mjs";
import { buildReport, renderOutput, exitCodeForReport } from "../lib/json.mjs";
import { statusFromCounts } from "../lib/result.mjs";
import { validate } from "../lib/schema-lite.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const PLATFORM_ROOT = join(here, "..", "..");
export const JOURNAL = ".ai-native/migration-journal.json";
export const CALLER = ".github/workflows/ai-native.yml";
export class MigrateError extends Error {}
const lockSchema = JSON.parse(readFileSync(join(PLATFORM_ROOT, "contracts", "lock.schema.json"), "utf8"));

/** Never touched, whatever their classification (plan SS18: "Conserva runs/, .audit/, ROADMAP.md y STATUS.md"). */
export const PROTECTED = ["runs/**", ".audit/**", "ROADMAP.md", "STATUS.md", "docs/producto/**", ".git/**", ".ai-native/**"];
/** Files the v2 TEMPLATE shipped AND the platform now provides. Only these may be retired, and only when IDENTICAL. */
export const PLATFORM_OWNED = [
  "scripts/**", "tests/**", ".agentic/**", ".agents/**", ".claude/**", ".codex/**", ".opencode/**", "evals/**",
  "CLAUDE.md", "CONSTITUTION.md", ".mcp.json", "opencode.json", "pytest.ini", "requirements-dev.txt",
  ".github/workflows/ci.yml", ".github/workflows/guard-develop-branch.yml",
  ".github/workflows/post-hitl-merge-gate.yml", ".github/workflows/post-merge-close-feature.yml",
];
const matcher = (globs) => { const res = globs.map(globToRegExp); return (p) => res.some((re) => re.test(p)); };
const isProtected = matcher(PROTECTED);
const isPlatformOwned = matcher(PLATFORM_OWNED);
const sha = (buf) => `sha256:${createHash("sha256").update(buf).digest("hex")}`;
// The Hash DB and the inventory hash TEXT files with CRLF normalised to LF (a checkout's autocrlf must not make a
// file look "modified"; parity/migrate-inventory.mjs). Anything compared against an inventory hash must do the same.
const isBinary = (buf) => buf.subarray(0, 8000).includes(0);
const normalizedSha = (buf) => sha(isBinary(buf) ? buf : Buffer.from(buf.toString("utf8").replaceAll("\r\n", "\n")));
const git = (cwd, ...a) => execFileSync("git", a, { cwd, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 }).trim();

function inventory(target) {
  const r = spawnSync(process.execPath, [join(PLATFORM_ROOT, "parity", "migrate-inventory.mjs"), "--target", target, "--json"], { encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });
  if (r.status !== 0 && !r.stdout) throw new MigrateError(`inventory failed: ${r.stderr}`);
  const report = JSON.parse(r.stdout);
  if (report.counts.UNKNOWN > 0) throw new MigrateError(`${report.counts.UNKNOWN} file(s) are UNKNOWN: a human must classify them before migrating`);
  return report;
}

function callerWorkflow({ repo, commit, baseBranch }) {
  const slug = repo.replace(/^github:/, "");
  return `name: ai-native

# Generated by \`ai-native migrate\`. Calls the platform's reusable L3 consumer gate, pinned by full SHA.
on:
  pull_request:
    branches: [${baseBranch}]

permissions:
  contents: read

jobs:
  l3:
    permissions:
      contents: read
    uses: ${slug}/.github/workflows/l3-consumer.yml@${commit}
`;
}

/** Pure given the inventory: what would happen. Throws on a dirty tree or in-flight v2 units. */
export function planMigration({ target, release, profile = "factory", tools = ["claude", "codex", "opencode"], baseBranch = "main", keep = [], releaseRoot = PLATFORM_ROOT }) {
  const root = resolve(target);
  if (git(root, "status", "--porcelain")) throw new MigrateError("working tree is not clean: commit or stash first (no migration over uncommitted changes)");
  const inv = inventory(root);
  if (inv.preflight.inFlightRoadmapItems?.length) throw new MigrateError(`in-flight v2 units block the migration: ${inv.preflight.inFlightRoadmapItems.join(", ")}`);
  const byPath = new Map(inv.files.map((f) => [f.path, f]));
  const retire = [];
  const keptIdentical = [];
  const keptLocal = [];
  for (const f of inv.files) {
    if (isProtected(f.path)) continue;
    if (f.classification === "IDENTICAL_TO_TEMPLATE") (isPlatformOwned(f.path) ? retire : keptIdentical).push({ path: f.path, sha256: `sha256:${f.sha256}` });
    else keptLocal.push({ path: f.path, classification: f.classification });
  }
  const retiring = new Set(retire.map((r) => r.path));
  const lockText = canonical({ schemaVersion: 1, platform: { repo: release.repo, version: release.version, commit: release.commit, digest: release.digest, channel: /-(alpha|rc)\./.test(release.version) ? "rc" : "stable" }, profiles: [profile], mcpProfiles: [], packs: [], overrides: {} });
  const add = { [LOCK_FILE]: lockText, [CALLER]: callerWorkflow({ repo: release.repo, commit: release.commit, baseBranch }) };
  for (const [p, c] of Object.entries(consumerFiles(releaseRoot, { tools }))) add[p] = c;
  const create = [];
  const replace = [];
  const collisions = [];
  for (const p of Object.keys(add).sort()) {
    const existing = byPath.get(p);
    if (!existing) { if (existsSync(join(root, p))) collisions.push({ path: p, reason: "exists but is untracked/ignored by the inventory" }); else create.push(p); continue; }
    if (retiring.has(p)) replace.push(p);
    else if (normalizedSha(Buffer.from(add[p])) === `sha256:${existing.sha256}`) continue; // already what v3 would write
    else collisions.push({ path: p, reason: `${existing.classification} v2 file (yours or product-owned)` });
  }
  const unresolved = collisions.filter((c) => !keep.includes(c.path));
  return { root, counts: inv.counts, retire, keptIdentical, keptLocal, create, replace, collisions, unresolved, kept: collisions.filter((c) => keep.includes(c.path)), add, blocked: unresolved.length > 0 };
}

export function applyMigration(args) {
  const planned = planMigration(args);
  const plan = args.hooks?.planOverride ? args.hooks.planOverride(planned) : planned; // test seam: simulate a plan that went stale
  const root = plan.root;
  if (existsSync(join(root, JOURNAL))) throw new MigrateError("a migration journal already exists; revert it first");
  if (plan.blocked) return { status: "BLOCKED", plan, written: [], removed: [] };
  const baseCommit = git(root, "rev-parse", "HEAD");
  // 0) the lock we are about to write must validate: a bad release (e.g. a malformed commit) aborts with the tree untouched
  const lockErrors = validate(JSON.parse(plan.add[LOCK_FILE]), lockSchema);
  if (lockErrors.length) throw new MigrateError(`the generated ${LOCK_FILE} does not validate: ${lockErrors.join("; ")}`);
  // 1) VERIFY every file we are about to delete, before touching anything: a mismatch aborts with the tree unchanged
  for (const r of plan.retire) {
    const full = join(root, r.path);
    if (readOrNull(full) === null || normalizedSha(readOrNull(full)) !== r.sha256) throw new MigrateError(`'${r.path}' changed between plan and apply; nothing was modified`);
  }
  for (const p of [...plan.create, ...plan.replace]) {
    if (existsSync(join(root, p)) && !plan.replace.includes(p)) throw new MigrateError(`'${p}' appeared between plan and apply; nothing was modified`);
  }
  // files a v3 file REPLACES existed in v2: remember their v2 hash so revert can put them back from the base commit
  const replacedV2 = plan.replace.map((p) => ({ path: p, sha256: plan.retire.find((r) => r.path === p).sha256 }));
  const created = [...plan.create, ...plan.replace].map((p) => ({ path: p, sha256: sha(Buffer.from(plan.add[p])) }));
  // 2) the journal is written BEFORE the first mutation, so an interruption at any point is recoverable with `revert`
  const journal = { schemaVersion: 1, baseCommit, platform: args.release, retired: plan.retire, replaced: replacedV2, created, kept: plan.kept, keptIdentical: plan.keptIdentical.length, keptLocal: plan.keptLocal.length };
  mkdirSync(join(root, ".ai-native"), { recursive: true });
  writeFileSync(join(root, JOURNAL), `${JSON.stringify(journal, null, 2)}
`, { flag: "wx" });
  // 3) mutate
  const removed = [];
  try {
    for (const r of plan.retire) {
      rmSync(join(root, r.path));
      removed.push(r);
    }
    args.hooks?.afterRetire?.(); // test seam: lets a test make the write phase fail after deletions started
    for (const c of created) {
      const full = join(root, c.path);
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, plan.add[c.path], { flag: "wx" });
    }
    const { errors } = readLock(root);
    if (errors.length) throw new MigrateError(`generated lock is invalid: ${errors.join("; ")}`);
  } catch (error) {
    // best effort: put everything back through the journal we already wrote
    try { revertMigration({ target: root }); } catch { /* the journal stays so the user can run `revert` */ }
    throw error;
  }
  return { status: "APPLIED", plan, written: created.map((c) => c.path), removed: removed.map((r) => r.path), baseCommit };
}

/**
 * A journal path is untrusted input and must be a plain relative path inside the repository, judged the same on
 * every OS: a Windows path ("C:/x", "\\host\share", "C:x") is absolute even when this process runs on Linux, where
 * path.isAbsolute() would say otherwise.
 */
export function assertSafeRelative(root, rel) {
  const s = String(rel ?? "");
  const bad = !s || s.includes("\0") || isAbsolute(s) || /^[A-Za-z]:/.test(s) || /^[\/]/.test(s) || s.split(/[\/]/).includes("..");
  if (bad || relative(root, resolve(root, s)).startsWith("..")) throw new MigrateError(`journal path escapes the repository: '${s}'`);
}

export function revertMigration({ target }) {
  const root = resolve(target);
  const jp = join(root, JOURNAL);
  const journalText = readOrNull(jp);
  if (journalText === null) throw new MigrateError("no migration journal; nothing to revert");
  const j = JSON.parse(journalText.toString("utf8"));
  // the journal lives in the repo, so it is untrusted input: every path must stay inside the root and be relative
  for (const entry of [...(j.created ?? []), ...(j.retired ?? [])]) assertSafeRelative(root, entry?.path);
  // A partial revert must be resumable: what an earlier run already undid is recorded in the journal and is never
  // re-judged (a restored v2 file legitimately no longer matches the v3 hash it was replaced by).
  const doneCreated = new Set(j.revertedCreated ?? []);
  const doneRestored = new Set(j.revertedRestored ?? []);
  const kept = [];
  const removed = [];
  for (const c of j.created) {
    if (doneCreated.has(c.path)) continue;
    const full = join(root, c.path);
    const current = readOrNull(full);
    if (current === null) { doneCreated.add(c.path); continue; }
    // the journal hash is of the bytes apply wrote (LF); a checkout with autocrlf rewrites line endings, which is
    // not a user edit, so compare the line-ending-normalised hash too (a real edit still differs either way)
    if (sha(current) !== c.sha256 && normalizedSha(current) !== c.sha256) { kept.push(c.path); continue; }
    rmSync(full);
    removed.push(c.path);
    doneCreated.add(c.path);
  }
  const restored = [];
  // `retired` holds every v2 file apply deleted, INCLUDING the ones a v3 file then took the place of (`replaced`)
  for (const r of j.retired) {
    if (doneRestored.has(r.path)) continue;
    // a retired file whose v3 replacement the user edited stays as the user's file: do not overwrite it with the v2 one
    if (kept.includes(r.path)) continue;
    // never overwrite a file that is there now: apply deleted it (or replaced it with a v3 file, removed above), so
    // anything present is something the user created afterwards
    // Extract the base-commit version with git into a scratch work tree (own index: the repo's index and tree are not
    // touched, autocrlf is honoured), then publish it with an EXCLUSIVE copy: if the user put a file there, it is kept.
    const scratch = mkdtempSync(join(tmpdir(), "ai-native-restore-"));
    try {
      const env = { ...process.env, GIT_INDEX_FILE: join(scratch, "index") };
      execFileSync("git", ["read-tree", j.baseCommit], { cwd: root, env });
      mkdirSync(join(scratch, "wt"), { recursive: true });
      execFileSync("git", ["--git-dir", join(root, ".git"), "--work-tree", join(scratch, "wt"), "checkout-index", "-f", "--", r.path], { cwd: scratch, env });
      const extracted = join(scratch, "wt", r.path);
      if (normalizedSha(readFileSync(extracted)) !== r.sha256) throw new MigrateError(`'${r.path}' at the base commit does not match the journal hash`);
      const target = join(root, r.path);
      mkdirSync(dirname(target), { recursive: true });
      try {
        copyFileSync(extracted, target, constants.COPYFILE_EXCL);
      } catch (error) {
        if (error.code === "EEXIST") { kept.push(r.path); continue; }
        throw error;
      }
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
    restored.push(r.path);
    doneRestored.add(r.path);
  }
  for (const p of removed) pruneEmpty(root, p);
  if (kept.length) {
    writeFileSync(jp, `${JSON.stringify({ ...j, revertedCreated: [...doneCreated], revertedRestored: [...doneRestored] }, null, 2)}
`);
  } else {
    rmSync(jp);
    pruneEmpty(root, JOURNAL);
  }
  return { status: kept.length ? "PARTIAL" : "REVERTED", removed, restored, kept };
}

/** Reads a file or returns null when it does not exist: no existsSync-then-read race. */
function readOrNull(path) {
  try {
    return readFileSync(path);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

function pruneEmpty(root, rel) {
  let dir = dirname(join(root, rel));
  while (dir.length > root.length) {
    let entries;
    try {
      entries = readdirSync(dir);
    } catch (error) {
      if (error.code === "ENOENT") { dir = dirname(dir); continue; } // already gone: keep walking up
      throw error;
    }
    if (entries.length) return;
    rmSync(dir, { recursive: true });
    dir = dirname(dir);
  }
}

function main() {
  const argv = process.argv.slice(2);
  const cmd = argv.shift();
  const values = (n) => argv.flatMap((a, i) => (a === n ? [argv[i + 1]] : []));
  const value = (n) => values(n)[0];
  const target = value("--target") ?? process.cwd();
  const errors = [];
  let data = {};
  try {
    const release = { repo: value("--repo"), version: value("--version"), commit: value("--commit"), digest: value("--digest") };
    const common = { target, release, profile: value("--profile") ?? "factory", tools: values("--tool").length ? values("--tool") : undefined, baseBranch: value("--base-branch") ?? "main", keep: values("--keep") };
    if (cmd === "revert") data = revertMigration({ target });
    else if (cmd === "plan" || cmd === "apply") {
      for (const k of ["repo", "version", "commit", "digest"]) if (!release[k]) throw new MigrateError(`--${k} is required`);
      const r = cmd === "plan" ? planMigration(common) : applyMigration(common);
      const p = r.plan ?? r;
      data = { mode: cmd, ...(r.status ? { result: r.status } : {}), counts: p.counts, retire: p.retire.length, replace: p.replace, create: p.create, keptIdentical: p.keptIdentical.length, keptLocal: p.keptLocal.length, collisions: p.collisions, unresolved: p.unresolved.map((c) => c.path) };
      if (r.status === "BLOCKED" || (cmd === "plan" && p.blocked)) errors.push(`collisions need a decision (--keep <path>): ${p.unresolved.map((c) => c.path).join(", ")}`);
    } else throw new MigrateError("usage: migrate plan|apply|revert --target <dir> ...");
  } catch (error) {
    errors.push(error.message);
  }
  const warnings = data.status === "PARTIAL" ? [`kept user-modified files: ${data.kept.join(", ")}`] : [];
  const report = buildReport({ status: statusFromCounts({ errors: errors.length, warnings: warnings.length }), errors, warnings, data: { migration: data } });
  console.log(renderOutput(report, { json: argv.includes("--json") }));
  process.exitCode = exitCodeForReport(report);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
