// Codex CLI adapter (M3.3, AGT-04/AGT-10; PAR-ADAPTERS). Derives
// .codex/config.toml, .codex/<role>.config.toml and .codex/README.md
// from core/agents.json + mcp/catalog.json. Ported from
// sync-agentic-adapters.ps1's ConvertTo-CodexConfig/ConvertTo-CodexProfile.
//
// AGT-10 gap this closes: TEMPLATE v2.0.5 never generated any README for
// the .codex/ setup it produced -- a consumer had no generated,
// always-current explanation of what config.toml was for or how to
// invoke Codex safely. .codex/README.md is new in M3.3.
//
// Entradas concretas de M2.3 (evaluation/compat/findings.md):
//   #2: `codex exec` must always be invoked with stdin explicitly closed
//       (`< /dev/null` or equivalent) -- confirmed to hang indefinitely
//       otherwise, waiting on EOF.
//   #3: on Windows, Codex's `sandbox_mode`/`approval_policy` do NOT
//       block `git push`/similar -- confirmed real execution, not a
//       sandbox denial. GIT_WRITE/REMOTE_WRITE/MERGE enforcement for
//       Codex must never be assumed to come from the client sandbox; the
//       real guarantee is server-side (trust-gate, P44, M4.3).
// Both are documented explicitly in the generated README rather than
// left to be rediscovered.
function toml(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function tomlArray(values) {
  return `[${values.map(toml).join(", ")}]`;
}

export function buildCodexConfigToml(agents, mcpCatalog) {
  const defaultRole = agents.roles.reviewer;
  const lines = [
    "# GENERATED by runtime/adapters/codex.mjs from core/agents.json + mcp/catalog.json. Do not edit manually.",
    "# Repo-local Codex defaults. Use this directory as CODEX_HOME.",
    `model = ${toml(defaultRole.codex.model)}`,
    `model_reasoning_effort = ${toml(defaultRole.codex.model_reasoning_effort)}`,
  ];
  for (const [name, server] of Object.entries(mcpCatalog.servers ?? {}).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push("", `[mcp_servers.${name}]`);
    if (server.type === "remote") {
      lines.push(`url = ${toml(server.url)}`);
      if (server.bearerTokenEnv) lines.push(`bearer_token_env_var = ${toml(server.bearerTokenEnv)}`);
    } else if (server.type === "local") {
      lines.push(`command = ${toml(server.command)}`);
      if (server.args) lines.push(`args = ${tomlArray(server.args)}`);
      if (server.env) {
        lines.push(`[mcp_servers.${name}.env]`);
        for (const [key, value] of Object.entries(server.env).sort(([a], [b]) => a.localeCompare(b))) {
          lines.push(`${key} = ${toml(value)}`);
        }
      }
    } else {
      throw new Error(`unsupported MCP server type for '${name}': ${server.type}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

export function buildCodexRoleProfileToml(role) {
  return `# GENERATED by runtime/adapters/codex.mjs from core/agents.json. Do not edit manually.
model = ${toml(role.codex.model)}
model_reasoning_effort = ${toml(role.codex.model_reasoning_effort)}
`;
}

export function buildCodexReadme() {
  return `# .codex/ (generated)

<!-- GENERATED by runtime/adapters/codex.mjs. Do not edit manually. -->

Codex CLI reads \`AGENTS.md\` natively at the repository root -- unlike
Claude Code, there is no bridge file here. \`config.toml\` (this
directory) sets the default model/reasoning effort and any MCP servers
declared in \`mcp/catalog.json\`; \`<role>.config.toml\` holds the
per-role override \`runtime/adapters\` derives from \`core/agents.json\`.

## Required invocation rule

Always invoke \`codex exec\` with stdin explicitly closed:

\`\`\`
codex exec --json "..." < /dev/null
\`\`\`

Confirmed during the M2.3 compatibility spike
(\`evaluation/compat/findings.md\`): a prompt passed as a positional
argument with stdin left open makes the process hang indefinitely
waiting for EOF ("Reading additional input from stdin...").

## Security note: sandbox_mode / approval_policy are not an enforcement boundary on Windows

Confirmed during the same spike: on Windows, neither
\`-s workspace-write\` nor \`-s read-only -c approval_policy=never\`
prevented \`git push\` from actually executing. Do not rely on Codex's
client-side sandbox for GIT_WRITE / REMOTE_WRITE / MERGE enforcement --
the real guarantee is server-side (\`trust-gate\`, P44, M4.3). This is a
documented, accepted residual risk for the Codex client on Windows, not
an unknown gap.
`;
}
