import { test } from "node:test";
import assert from "node:assert/strict";
import { buildCodexConfigToml, buildCodexRoleProfileToml, buildCodexReadme } from "./codex.mjs";

const AGENTS = { roles: { reviewer: { codex: { model: "gpt-5.5", model_reasoning_effort: "high" } } } };

test("buildCodexConfigToml uses the reviewer role as the default model", () => {
  const toml = buildCodexConfigToml(AGENTS, { servers: {} });
  assert.match(toml, /^model = "gpt-5\.5"/m);
  assert.match(toml, /model_reasoning_effort = "high"/);
});

test("buildCodexConfigToml renders a local mcp server block with args and env, sorted", () => {
  const catalog = { servers: { local1: { type: "local", command: "node", args: ["server.js"], env: { B: "2", A: "1" } } } };
  const toml = buildCodexConfigToml(AGENTS, catalog);
  assert.match(toml, /\[mcp_servers\.local1\]/);
  assert.match(toml, /command = "node"/);
  assert.match(toml, /args = \["server\.js"\]/);
  assert.match(toml, /\[mcp_servers\.local1\.env\]\nA = "1"\nB = "2"/);
});

test("buildCodexConfigToml renders a remote mcp server block", () => {
  const catalog = { servers: { remote1: { type: "remote", url: "https://example.invalid", bearerTokenEnv: "TOKEN" } } };
  const toml = buildCodexConfigToml(AGENTS, catalog);
  assert.match(toml, /url = "https:\/\/example\.invalid"/);
  assert.match(toml, /bearer_token_env_var = "TOKEN"/);
});

test("buildCodexConfigToml escapes quotes and backslashes in TOML strings", () => {
  const catalog = { servers: { x: { type: "local", command: 'C:\\path\\with"quote' } } };
  const toml = buildCodexConfigToml(AGENTS, catalog);
  assert.match(toml, /command = "C:\\\\path\\\\with\\"quote"/);
});

test("buildCodexRoleProfileToml renders a per-role profile", () => {
  const toml = buildCodexRoleProfileToml({ codex: { model: "gpt-5.5", model_reasoning_effort: "high" } });
  assert.match(toml, /model = "gpt-5\.5"/);
  assert.match(toml, /^# GENERATED by runtime\/adapters\/codex\.mjs/);
});

// AGT-10: TEMPLATE v2.0.5 never generated a README for .codex/ setup.
test("buildCodexReadme documents the stdin-closed invocation rule and the Windows sandbox risk (M2.3 findings #2/#3)", () => {
  const readme = buildCodexReadme();
  assert.match(readme, /< \/dev\/null/);
  assert.match(readme, /sandbox_mode/);
  assert.match(readme, /trust-gate/);
});
