#!/usr/bin/env node
// Adapter sync/check orchestrator (M3.3, AGT-04; PAR-ADAPTERS). Derives
// every per-tool file from core/agents.json + mcp/catalog.json via
// claude.mjs/codex.mjs/opencode.mjs, and the lazy skill mirrors via
// skills.mjs. Ported from sync-agentic-adapters.ps1, with its -AutoFix
// path's known bugs (see skills.mjs's header) eliminated by construction:
// `sync()` and `check()` share the exact same generated-content map, so
// there is no separate "parse a problem string and re-derive a path"
// step that could disagree with it.
import { existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, unlinkSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { governedCatalog, DEFAULT_GATEWAY_SCRIPT } from "./gateway.mjs";
import { checkEntryPoints, loadAgents, loadMcpCatalog, loadRolePrompt } from "./sources.mjs";
import { buildClaudeBridge, buildClaudeMcpJson, buildClaudeAgentFile } from "./claude.mjs";
import { buildCodexConfigToml, buildCodexRoleProfileToml, buildCodexReadme } from "./codex.mjs";
import { buildOpenCodeConfig } from "./opencode.mjs";
import { loadSkillsRegistry, selectSkills, materialize as materializeSkills, check as checkSkills } from "./skills.mjs";
import { buildReport, renderOutput, exitCodeForReport } from "../lib/json.mjs";
import { RESULT_STATUS, statusFromCounts } from "../lib/result.mjs";

export const ALL_TOOLS = ["claude", "codex", "opencode"];

/** Legacy (TEMPLATE v2.0.5) adapter paths that must never reappear once a
 * repo has migrated to runtime/adapters-generated files. */
export const LEGACY_PATHS = [
  ".codex/prompts/analyst-agent.md",
  ".codex/prompts/reviewer-agent.md",
  ".codex/prompts/builder-agent.md",
  ".codex/prompts/qa-agent.md",
  ".opencode/agent/analyst-agent.md",
  ".opencode/agent/reviewer-agent.md",
  ".opencode/agent/builder-agent.md",
  ".opencode/agent/qa-agent.md",
];

/** { relativePath: content } for every tool file this repo's core/
 * sources currently derive to, filtered to `tools` (default: all 3). */
export function buildToolFiles(root, { tools = ALL_TOOLS, mcpProfile = "none", gatewayScript = DEFAULT_GATEWAY_SCRIPT, opencodeRolesDir = null } = {}) {
  const agents = loadAgents(root);
  // tools never see the raw catalog: only the gateway (runtime/adapters/gateway.mjs)
  const mcp = governedCatalog({ catalog: loadMcpCatalog(root), root, profile: mcpProfile, script: gatewayScript });
  const files = {};

  if (tools.includes("claude")) {
    files["CLAUDE.md"] = buildClaudeBridge();
    files[".mcp.json"] = buildClaudeMcpJson(mcp);
  }
  if (tools.includes("codex")) {
    files[".codex/config.toml"] = buildCodexConfigToml(agents, mcp);
    files[".codex/README.md"] = buildCodexReadme();
  }
  if (tools.includes("opencode")) {
    files["opencode.json"] = buildOpenCodeConfig(agents, mcp, { rolesDir: opencodeRolesDir });
  }

  for (const [name, role] of Object.entries(agents.roles)) {
    const prompt = loadRolePrompt(root, role);
    if (tools.includes("claude")) {
      files[`.claude/agents/${name}.md`] = buildClaudeAgentFile(name, role, prompt, agents.generatedNotice);
    }
    if (tools.includes("codex")) {
      files[`.codex/${name}.config.toml`] = buildCodexRoleProfileToml(role);
    }
    if (tools.includes("opencode") && opencodeRolesDir) files[`${opencodeRolesDir}/${name}.md`] = prompt;
  }

  return files;
}

/**
 * Adapter-owned files (`.claude/agents/*.md`, `.codex/<role>.config.toml`)
 * whose role no longer exists in core/agents.json. These two directories/
 * suffixes are exclusively owned by this module's own output -- no
 * marker-comment sniffing needed (TEMPLATE v2.0.5's AutoFix only pruned
 * these when a "GENERATED by..." marker matched, which is one more
 * string-matching step that could silently skip a real orphan; scoping
 * by directory/suffix is simpler and cannot miss one).
 */
export function findObsoleteAdapters(root, agents) {
  const canonicalNames = new Set(Object.keys(agents.roles));
  const obsolete = [];

  const claudeAgentsDir = join(root, ".claude", "agents");
  if (existsSync(claudeAgentsDir)) {
    for (const file of readdirSync(claudeAgentsDir)) {
      if (file.endsWith(".md") && !canonicalNames.has(file.slice(0, -3))) {
        obsolete.push(`.claude/agents/${file}`);
      }
    }
  }

  const codexDir = join(root, ".codex");
  if (existsSync(codexDir)) {
    for (const file of readdirSync(codexDir)) {
      if (file.endsWith(".config.toml") && file !== "config.toml" && !canonicalNames.has(file.slice(0, -".config.toml".length))) {
        obsolete.push(`.codex/${file}`);
      }
    }
  }

  return obsolete;
}

function legacyPathsPresent(root) {
  return LEGACY_PATHS.filter((rel) => existsSync(join(root, rel)));
}

/** Writes every generated tool file + materializes the selected skills. */
export function sync(root, { tools = ALL_TOOLS, profile, role, level } = {}) {
  const files = buildToolFiles(root, { tools });
  for (const [relativePath, content] of Object.entries(files)) {
    const fullPath = join(root, relativePath);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, content, "utf8");
  }
  for (const relativePath of legacyPathsPresent(root)) {
    rmSync(join(root, relativePath), { force: true });
  }
  const agents = loadAgents(root);
  for (const relativePath of findObsoleteAdapters(root, agents)) {
    const fullPath = join(root, relativePath);
    if (existsSync(fullPath)) {
      unlinkSync(fullPath);
    }
  }
  const registry = loadSkillsRegistry(root);
  const skillIds = selectSkills(registry, { profile, role, level });
  materializeSkills(root, skillIds);
  return { files: Object.keys(files), skills: skillIds };
}

/** Read-only: every divergence between expected and on-disk state. */
export function check(root, { tools = ALL_TOOLS, profile, role, level } = {}) {
  const problems = [...checkEntryPoints(root)];

  const files = buildToolFiles(root, { tools });
  for (const [relativePath, expected] of Object.entries(files)) {
    const fullPath = join(root, relativePath);
    if (!existsSync(fullPath)) {
      problems.push(`missing generated adapter: ${relativePath}`);
      continue;
    }
    const actual = readFileSync(fullPath, "utf8");
    if (actual !== expected) {
      problems.push(`generated adapter outdated or divergent: ${relativePath}`);
    }
  }

  for (const relativePath of legacyPathsPresent(root)) {
    problems.push(`legacy non-canonical adapter present: ${relativePath}`);
  }

  const agents = loadAgents(root);
  for (const relativePath of findObsoleteAdapters(root, agents)) {
    problems.push(`obsolete generated adapter: ${relativePath}`);
  }

  const registry = loadSkillsRegistry(root);
  const skillIds = selectSkills(registry, { profile, role, level });
  problems.push(...checkSkills(root, skillIds));

  return problems;
}

async function main() {
  const here = dirname(fileURLToPath(import.meta.url));
  const root = join(here, "..", "..");
  const args = process.argv.slice(2);
  const json = args.includes("--json");
  const isCheck = args.includes("--check");
  const getOption = (flag) => {
    const idx = args.indexOf(flag);
    return idx >= 0 ? args[idx + 1] : undefined;
  };
  const opts = { profile: getOption("--profile"), role: getOption("--role"), level: getOption("--level") };

  const problems = isCheck ? check(root, opts) : (sync(root, opts), []);
  const status = statusFromCounts({ errors: problems.length, warnings: 0 });
  const report = buildReport({ status, errors: problems, warnings: [], data: { mode: isCheck ? "check" : "sync" } });
  console.log(renderOutput(report, { json }));
  process.exit(exitCodeForReport(report, { strict: true }));
}

const isMain = process.argv[1] && resolve(fileURLToPath(import.meta.url)) === resolve(process.argv[1]);
if (isMain) {
  main();
}
